const sampleMaidData = [
  {
    username: "maid1",
    location: { type: "Point", coordinates: [77.21, 28.61] },
    contact: "9000000001",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
    services: ["cleaning", "cooking"],
    experience: 2,
    rate: 250,
    serviceArea: "Connaught Place",
    city: "Delhi",
    country: "India",
  },
  {
    username: "maid2",
    location: { type: "Point", coordinates: [72.88, 19.07] },
    contact: "9000000002",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    services: ["laundry"],
    experience: 3,
    rate: 220,
    serviceArea: "Andheri",
    city: "Mumbai",
    country: "India",
  },
  {
    username: "maid3",
    location: { type: "Point", coordinates: [77.59, 12.97] },
    contact: "9000000003",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
    services: ["cleaning"],
    experience: 1,
    rate: 200,
    serviceArea: "Indiranagar",
    city: "Bangalore",
    country: "India",
  },
  {
    username: "maid4",
    location: { type: "Point", coordinates: [75.79, 26.91] },
    contact: "9000000004",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    services: ["cooking", "dishWashing"],
    experience: 4,
    rate: 300,
    serviceArea: "Malviya Nagar",
    city: "Jaipur",
    country: "India",
  },
  {
    username: "maid5",
    location: { type: "Point", coordinates: [78.48, 17.38] },
    contact: "9000000005",
    image: "https://randomuser.me/api/portraits/women/5.jpg",
    services: ["laundry", "cleaning"],
    experience: 5,
    rate: 350,
    serviceArea: "Banjara Hills",
    city: "Hyderabad",
    country: "India",
  },
  {
    username: "maid6",
    location: { type: "Point", coordinates: [80.27, 13.08] },
    contact: "9000000006",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
    services: ["cooking"],
    experience: 2,
    rate: 270,
    serviceArea: "T Nagar",
    city: "Chennai",
    country: "India",
  },
  {
    username: "maid7",
    location: { type: "Point", coordinates: [88.36, 22.57] },
    contact: "9000000007",
    image: "https://randomuser.me/api/portraits/women/7.jpg",
    services: ["dishWashing"],
    experience: 3,
    rate: 230,
    serviceArea: "Salt Lake",
    city: "Kolkata",
    country: "India",
  },
  {
    username: "maid8",
    location: { type: "Point", coordinates: [76.77, 30.73] },
    contact: "9000000008",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
    services: ["cleaning", "laundry"],
    experience: 4,
    rate: 260,
    serviceArea: "Sector 17",
    city: "Chandigarh",
    country: "India",
  },
  {
    username: "maid9",
    location: { type: "Point", coordinates: [73.85, 18.52] },
    contact: "9000000009",
    image: "https://randomuser.me/api/portraits/women/9.jpg",
    services: ["cooking"],
    experience: 6,
    rate: 400,
    serviceArea: "Shivaji Nagar",
    city: "Pune",
    country: "India",
  },
  {
    username: "maid10",
    location: { type: "Point", coordinates: [72.57, 23.02] },
    contact: "9000000010",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    services: ["cleaning"],
    experience: 2,
    rate: 210,
    serviceArea: "Navrangpura",
    city: "Ahmedabad",
    country: "India",
  },

  {
    username: "maid11",
    location: { type: "Point", coordinates: [77.1, 28.7] },
    contact: "9000000011",
    image: "https://randomuser.me/api/portraits/women/11.jpg",
    services: ["laundry"],
    experience: 3,
    rate: 220,
    serviceArea: "Rohini",
    city: "Delhi",
    country: "India",
  },
  {
    username: "maid12",
    location: { type: "Point", coordinates: [72.83, 19.11] },
    contact: "9000000012",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    services: ["cleaning"],
    experience: 5,
    rate: 300,
    serviceArea: "Bandra",
    city: "Mumbai",
    country: "India",
  },
  {
    username: "maid13",
    location: { type: "Point", coordinates: [77.64, 12.98] },
    contact: "9000000013",
    image: "https://randomuser.me/api/portraits/women/13.jpg",
    services: ["cooking", "laundry"],
    experience: 4,
    rate: 350,
    serviceArea: "Whitefield",
    city: "Bangalore",
    country: "India",
  },
  {
    username: "maid14",
    location: { type: "Point", coordinates: [75.75, 26.85] },
    contact: "9000000014",
    image: "https://randomuser.me/api/portraits/women/14.jpg",
    services: ["dishWashing"],
    experience: 2,
    rate: 200,
    serviceArea: "Vaishali Nagar",
    city: "Jaipur",
    country: "India",
  },
  {
    username: "maid15",
    location: { type: "Point", coordinates: [78.5, 17.4] },
    contact: "9000000015",
    image: "https://randomuser.me/api/portraits/women/15.jpg",
    services: ["cleaning", "cooking"],
    experience: 6,
    rate: 420,
    serviceArea: "Gachibowli",
    city: "Hyderabad",
    country: "India",
  },

  {
    username: "maid16",
    location: { type: "Point", coordinates: [80.3, 13.05] },
    contact: "9000000016",
    image: "https://randomuser.me/api/portraits/women/16.jpg",
    services: ["laundry"],
    experience: 3,
    rate: 240,
    serviceArea: "Adyar",
    city: "Chennai",
    country: "India",
  },
  {
    username: "maid17",
    location: { type: "Point", coordinates: [88.4, 22.6] },
    contact: "9000000017",
    image: "https://randomuser.me/api/portraits/women/17.jpg",
    services: ["cleaning"],
    experience: 2,
    rate: 210,
    serviceArea: "Howrah",
    city: "Kolkata",
    country: "India",
  },
  {
    username: "maid18",
    location: { type: "Point", coordinates: [76.8, 30.7] },
    contact: "9000000018",
    image: "https://randomuser.me/api/portraits/women/18.jpg",
    services: ["cooking"],
    experience: 5,
    rate: 360,
    serviceArea: "Sector 22",
    city: "Chandigarh",
    country: "India",
  },
  {
    username: "maid19",
    location: { type: "Point", coordinates: [73.9, 18.55] },
    contact: "9000000019",
    image: "https://randomuser.me/api/portraits/women/19.jpg",
    services: ["dishWashing"],
    experience: 1,
    rate: 180,
    serviceArea: "Kothrud",
    city: "Pune",
    country: "India",
  },
  {
    username: "maid20",
    location: { type: "Point", coordinates: [72.6, 23.03] },
    contact: "9000000020",
    image: "https://randomuser.me/api/portraits/women/20.jpg",
    services: ["cleaning", "laundry"],
    experience: 4,
    rate: 260,
    serviceArea: "Satellite",
    city: "Ahmedabad",
    country: "India",
  },

  {
    username: "maid21",
    location: { type: "Point", coordinates: [77.25, 28.55] },
    contact: "9000000021",
    image: "https://randomuser.me/api/portraits/women/21.jpg",
    services: ["cooking"],
    experience: 3,
    rate: 300,
    serviceArea: "Lajpat Nagar",
    city: "Delhi",
    country: "India",
  },
  {
    username: "maid22",
    location: { type: "Point", coordinates: [72.85, 19.2] },
    contact: "9000000022",
    image: "https://randomuser.me/api/portraits/women/22.jpg",
    services: ["laundry"],
    experience: 2,
    rate: 210,
    serviceArea: "Borivali",
    city: "Mumbai",
    country: "India",
  },
  {
    username: "maid23",
    location: { type: "Point", coordinates: [77.7, 13.0] },
    contact: "9000000023",
    image: "https://randomuser.me/api/portraits/women/23.jpg",
    services: ["cleaning"],
    experience: 4,
    rate: 280,
    serviceArea: "Yelahanka",
    city: "Bangalore",
    country: "India",
  },
  {
    username: "maid24",
    location: { type: "Point", coordinates: [75.8, 26.95] },
    contact: "9000000024",
    image: "https://randomuser.me/api/portraits/women/24.jpg",
    services: ["dishWashing"],
    experience: 3,
    rate: 230,
    serviceArea: "Jagatpura",
    city: "Jaipur",
    country: "India",
  },
  {
    username: "maid25",
    location: { type: "Point", coordinates: [78.45, 17.42] },
    contact: "9000000025",
    image: "https://randomuser.me/api/portraits/women/25.jpg",
    services: ["cleaning", "cooking"],
    experience: 5,
    rate: 390,
    serviceArea: "Madhapur",
    city: "Hyderabad",
    country: "India",
  },

  {
    username: "maid26",
    location: { type: "Point", coordinates: [80.25, 13.1] },
    contact: "9000000026",
    image: "https://randomuser.me/api/portraits/women/26.jpg",
    services: ["laundry"],
    experience: 2,
    rate: 220,
    serviceArea: "Velachery",
    city: "Chennai",
    country: "India",
  },
  {
    username: "maid27",
    location: { type: "Point", coordinates: [88.3, 22.5] },
    contact: "9000000027",
    image: "https://randomuser.me/api/portraits/women/27.jpg",
    services: ["cleaning"],
    experience: 3,
    rate: 240,
    serviceArea: "Park Street",
    city: "Kolkata",
    country: "India",
  },
  {
    username: "maid28",
    location: { type: "Point", coordinates: [76.75, 30.75] },
    contact: "9000000028",
    image: "https://randomuser.me/api/portraits/women/28.jpg",
    services: ["cooking"],
    experience: 4,
    rate: 330,
    serviceArea: "Sector 35",
    city: "Chandigarh",
    country: "India",
  },
  {
    username: "maid29",
    location: { type: "Point", coordinates: [73.8, 18.6] },
    contact: "9000000029",
    image: "https://randomuser.me/api/portraits/women/29.jpg",
    services: ["dishWashing"],
    experience: 1,
    rate: 190,
    serviceArea: "Wakad",
    city: "Pune",
    country: "India",
  },
  {
    username: "maid30",
    location: { type: "Point", coordinates: [72.55, 23.0] },
    contact: "9000000030",
    image: "https://randomuser.me/api/portraits/women/30.jpg",
    services: ["cleaning", "laundry"],
    experience: 4,
    rate: 270,
    serviceArea: "Maninagar",
    city: "Ahmedabad",
    country: "India",
  },
];

module.exports = { sampleMaidData };
