const sampleUserData = [
  {
    name: "John Doe",
    email: "john.doe@example.com",
    area: "Downtown",
    city: "San Francisco",
    country: "USA",
  },
  {
    name: "Jane Smith",
    email: "jane.smith@example.com",
    area: "Eastside",
    city: "New York",
    country: "USA",
  },
  {
    name: "Carlos Ramirez",
    email: "carlos.r@example.com",
    area: "La Roma",
    city: "Mexico City",
    country: "Mexico",
  },
  {
    name: "Aisha Khan",
    email: "aisha.k@example.com",
    area: "Jumeirah",
    city: "Dubai",
    country: "UAE",
  },
  {
    name: "Kenji Tanaka",
    email: "kenji.t@example.com",
    area: "Shibuya",
    city: "Tokyo",
    country: "Japan",
  },
  {
    name: "Li Wei",
    email: "li.wei@example.com",
    area: "Chaoyang",
    city: "Beijing",
    country: "China",
  },
  {
    name: "Maria Garcia",
    email: "maria.g@example.com",
    area: "Palermo",
    city: "Buenos Aires",
    country: "Argentina",
  },
  {
    name: "Anjali Desai",
    email: "anjali.d@example.com",
    area: "Bandra",
    city: "Mumbai",
    country: "India",
  },
  {
    name: "Alex Johnson",
    email: "alex.j@example.com",
    area: "Richmond",
    city: "London",
    country: "UK",
  },
  {
    name: "Sofia Petrova",
    email: "sofia.p@example.com",
    area: "Pravoberezhny",
    city: "Moscow",
    country: "Russia",
  },
  {
    name: "Frank Miller",
    email: "frank.m@example.com",
    area: "North Vancouver",
    city: "Vancouver",
    country: "Canada",
  },
  {
    name: "Olivia Jones",
    email: "olivia.j@example.com",
    area: "Manhattan",
    city: "New York",
    country: "USA",
  },
  {
    name: "Javier Lopez",
    email: "javier.l@example.com",
    area: "Gotico",
    city: "Barcelona",
    country: "Spain",
  },
  {
    name: "Chloe Dubois",
    email: "chloe.d@example.com",
    area: "Le Marais",
    city: "Paris",
    country: "France",
  },
  {
    name: "Omar Hussein",
    email: "omar.h@example.com",
    area: "Maadi",
    city: "Cairo",
    country: "Egypt",
  },
  {
    name: "Isabelle Chen",
    email: "isabelle.c@example.com",
    area: "Central",
    city: "Hong Kong",
    country: "China",
  },
  {
    name: "Ricardo Sanchez",
    email: "ricardo.s@example.com",
    area: "Copacabana",
    city: "Rio de Janeiro",
    country: "Brazil",
  },
  {
    name: "Mia Kim",
    email: "mia.k@example.com",
    area: "Gangnam",
    city: "Seoul",
    country: "South Korea",
  },
  {
    name: "Benjamin Wright",
    email: "ben.w@example.com",
    area: "Sydney CBD",
    city: "Sydney",
    country: "Australia",
  },
  {
    name: "Sana Malik",
    email: "sana.m@example.com",
    area: "Gulberg",
    city: "Lahore",
    country: "Pakistan",
  },
];

module.exports = { sampleUserData };
